* GNU Emacs manual
[[https://www.gnu.org/software/emacs/manual/emacs.html][GNU Emacs manual]] 日本語版
** 出典
[[http://echo.2ch.net/test/read.cgi/unix/1449824135/606-][(2ch.net) Emacs Part 49 #606-]] より。
** Copyright
#+BEGIN_QUOTE
This is the Seventeenth edition of the GNU Emacs Manual,
updated for Emacs version 24.5.

Copyright © 2015–2016 Ayanokoji Takesi <ayanokoji.takesi@gmail.com>
Copyright © 1985–1987, 1993–2015 Free Software Foundation, Inc.

Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU Free Documentation License, Version 1.3 or any later
version published by the Free Software Foundation; with the Invariant Sections
being “The GNU Manifesto,” “Distribution” and “GNU GENERAL PUBLIC
LICENSE,” with the Front-Cover Texts being “A GNU Manual,” and with the
Back-Cover Texts as in (a) below. A copy of the license is included in the
section entitled “GNU Free Documentation License.”
(a) The FSF’s Back-Cover Text is: “You have the freedom to copy and modify
this GNU manual. Buying copies from the FSF supports it in developing GNU
and promoting software freedom.”

Published by the Free Software Foundation
51 Franklin Street, Fifth Floor
Boston, MA 02110-1301 USA
ISBN 978-0-9831592-4-7
Cover art by Etienne Suvasa; cover design by Matt Lee.
#+END_QUOTE
