;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-delete-forward
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        goto-line
        kill-region
        markdown-exdent-or-delete
        mouse-set-region
        my/seq-end
        my/seq-home
        org-end-of-line
        org-self-insert-command
        paredit-forward-delete
        paredit-kill
        sp-remove-active-pair-overlay
        subword-left
        subword-right
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-paren
        subword-right
        ))
