;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-pound
        c-electric-semi&comma
        c-electric-star
        my/seq-end
        paredit-forward-delete
        sp-remove-active-pair-overlay
        subword-right
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-paren
        subword-right
        ))
