;;; my-packages.el --- Lisp packages installation  -*- lexical-binding: t -*-

;;; Commentary:

;; This file is a script for Lisp packages installation.

;;; Code:

(require 'package)
(require 'recentf)

(setq recentf-auto-cleanup 'never)
(add-to-list 'recentf-exclude "/elpa/.*-autoloads\\.el\\'")

(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)

(setopt package-selected-packages '(key-chord php-mode))

(package-initialize)

(unless (package-installed-p 'borg)
 (package-install 'borg))

(unless (package-installed-p 'emacsql-sqlite-module)
 (package-install 'emacsql-sqlite-module))

(require 'borg-elpa)
(borg-elpa-initialize)

(require 'wiz)
(require 'wiz-key)
(require 'wiz-env)
(require 'wiz-pkgs)

(wiz wiz-pkgs
  :init
  (lambda ()
    (setopt wiz-pkgs-enable-log t)))

(wiz-pkg exec-path-from-shell)
(unless (eval-when-compile (eq window-system 'nt))
  (wiz-envs "PATH" "SSH_AUTH_SOCK" "SSH_AGENT_PID"))

(wiz-pkg cape)
(wiz-pkg modus-themes)
(wiz-pkg 2048-game)
;; (wiz-pkg all-the-icons-dired)
(wiz-pkg annotate)
(wiz-pkg apache-mode)
(wiz-pkg auto-minor-mode)
;; (wiz-pkg beacon)
(wiz-pkg bind-key)
(wiz-pkg composer)
(wiz-pkg copy-file-on-save)
(wiz-pkg copyit)
(wiz-pkg copyit-pandoc)
(wiz-pkg consult-ls-git)
;; (wiz-pkg cov)
(wiz-pkg crux)
(wiz-pkg csv-mode)
(wiz-pkg ctrlf)
;; (wiz-pkg dash)
;; (wiz-pkg dash-at-point)
(wiz-pkg datetime-format)
(wiz-pkg diminish)
(wiz-pkg dired-k)
(wiz-pkg dired-preview)
(wiz-pkg direx)
(wiz-pkg dist-file-mode)
(wiz-pkg dockerfile-mode)
(wiz-pkg drag-stuff)
(wiz-pkg eask-mode)
(wiz-pkg eat)
(wiz-pkg editorconfig)
(wiz-pkg elisp-slime-nav)
(wiz-pkg elscreen)
(wiz-pkg emacsql-mysql)
(wiz-pkg emmet-mode)
;; (wiz-pkg enh-ruby-mode)
(wiz-pkg eshell-fringe-status)
(wiz-pkg expand-region)
(wiz-pkg f)
;; (wiz-pkg faceup)
(wiz-pkg flycheck)
(wiz-pkg flycheck-cask)
(wiz-pkg flycheck-eask)
(wiz-pkg flycheck-elsa)
(wiz-pkg flycheck-package)
(wiz-pkg font-lock-profiler)
(wiz-pkg font-lock-studio)
(wiz-pkg format-sql)
;; (wiz-pkg geben)
(wiz-pkg geiser)
(wiz-pkg gcmh)
(wiz-pkg git-modes)
(wiz-pkg go-mode)
(wiz-pkg google-translate)
(wiz-pkg haskell-mode)
;; (wiz-pkg hierarchy)
(wiz-pkg highlight-indent-guides)
(wiz-pkg highlight-refontification)
(wiz-pkg ht)
(wiz-pkg http)
(wiz-pkg hydra)
(wiz-pkg inf-ruby)
(wiz-pkg init-open-recentf)
(wiz-pkg ivs-edit)
(wiz-pkg ivy)
(wiz-pkg jade-mode)
(wiz-pkg jetbrains)
;; (wiz-pkg js2-mode)
(wiz-pkg jsonian)
(wiz-pkg keyfreq)
(wiz-pkg lispxmp)
(wiz-pkg logview)
(wiz-pkg lua-mode)
(wiz-pkg lsp-ui)
(wiz-pkg macrostep)
(wiz-pkg magic-filetype)
(wiz-pkg magit)
;; (wiz-pkg magit-delta)
(wiz-pkg magit-find-file)
(wiz-pkg markdown-mode)
(wiz-pkg maruo-macro-mode)
(wiz-pkg move-text)
(wiz-pkg multiple-cursors)
(wiz-pkg nameless)
(wiz-pkg neon-mode)
(wiz-pkg nginx-mode)
;; (wiz-pkg nim-mode)
(wiz-pkg nyan-mode)
(wiz-pkg open-junk-file)
;; (wiz-pkg org-table-sticky-header)
(wiz-pkg ob-sql-mode)
(wiz-pkg osx-lib)
(wiz-pkg ov)
;; (wiz-pkg ox-ioslide)
(wiz-pkg page-break-lines)
(wiz-pkg pandoc)
(wiz-pkg paredit)
;;(wiz-pkg pcap-mode)
(wiz-pkg pdf-tools)
(wiz-pkg phan)
(wiz-pkg php-mode)
(wiz-pkg phpt-mode)
(wiz-pkg phpactor)
(wiz-pkg posframe)
(wiz-pkg projectile)
(wiz-pkg flycheck-posframe)
(wiz-pkg flycheck-phpstan)
(wiz-pkg phpunit)
(wiz-pkg presentation)
(wiz-pkg popwin)
(wiz-pkg projectile)
(wiz-pkg psysh)
(wiz-pkg pulsar)
(wiz-pkg quickrun)
(wiz-pkg rainbow-mode)
(wiz-pkg region-convert)
;; (wiz-pkg request-deferred)
;; (wiz-pkg restclient)
(wiz-pkg right-click-context)
(wiz-pkg rg)
(wiz-pkg robots-txt-mode)
(wiz-pkg s)
(wiz-pkg scss-mode)
;; (wiz-pkg shx)
;;(wiz-pkg sly)
(wiz-pkg smart-jump)
;; (wiz-pkg smart-newline)
(wiz-pkg smartparens)
(wiz-pkg smartrep)
;; (wiz-pkg smex)
(wiz-pkg smooth-scroll)
(wiz-pkg surround)
(wiz-pkg sql-indent)
(wiz-pkg ssh-config-mode)
(wiz-pkg threes)
(wiz-pkg tide)
(wiz-pkg toml)
(wiz-pkg toml-mode)
(wiz-pkg typescript-mode)
(wiz-pkg ucs-utils)
(wiz-pkg undo-fu)
(wiz-pkg untitled-new-buffer)
(wiz-pkg vi-tilde-fringe)
(wiz-pkg vimrc-mode)
(wiz-pkg visual-regexp)
(wiz-pkg vlf)
;; (wiz-pkg vterm)
(wiz-pkg volatile-highlights)
(wiz-pkg wc-mode)
(wiz-pkg web-mode)
(wiz-pkg which-key)
(wiz-pkg writeroom-mode)
(wiz-pkg yafolding)
(wiz-pkg yaml-mode)
(wiz-pkg yard-mode)
(wiz-pkg yasnippet)
(wiz-pkg yasnippet-snippets)
(wiz-pkg company-tabnine)
(wiz-pkg archive-phar)
(wiz-pkg nov)
(wiz-pkg prescient)
(wiz-pkg corfu-prescient)

;;; my-packages.el ends here
